package ru.itis.itis_android_inception_24.utils

object ScreenTags {
    const val LIST_CONTENT_TAG = "LIST_CONTENT"
    const val MULTIPLE_TYPES_LIST_TAG = "MULTIPLE_TYPES_LIST"
    const val COMPOSE_SAMPLE_FRAGMENT_TAG = "COMPOSE_SAMPLE_FRAGMENT"
    const val NOTIFICATIONS_FRAGMENT_TAG = "NOTIFICATIONS_FRAGMENT"
    const val PROFILE_FRAGMENT_TAG = "PROFILE_FRAGMENT"
}